package p000a.p001a.p002a.p007e.p008a;

public enum EnumC0018a {
    NON,
    ERROR_PATH,
    ERROR_OPEN_CONNECTION,
    ERROR_SOCKET_CONNECTTION,
    ERROR_GET_FILE,
    ERROR_SAVE_FILE,
    ERROR_USER,
    ERROR_CLOSE_CONNECTION,
    ERROR_UNKNOWN
}
