package com.brother.sdk.common.socket.scan;

public enum ScanState {
    Success,
    ErrorScanNoSupportedProtocol,
    ErrorScanInvalidArgument,
    ErrorScanConnectionFailure,
    ErrorScanDeviceNotFound,
    ErrorScanDocumentJam,
    ErrorScanCoverOpen,
    ErrorScanScannerBusy,
    ErrorScanDeviceMemoryFull,
    ErrorScanSecureLock,
    ErrorScanADFCoverOpen,
    ErrorScanDuplexSizeTooLarge,
    ErrorScanMultiFeed,
    ErrorScanFBCoverOpen,
    ErrorScanCardTrayOpen,
    ErrorScanCardTrayClose,
    ErrorScanNoPaper,
    ErrorScanCancelAcknowledged,
    ErrorScanStopKeyPressed,
    ErrorScanInvalidCommand,
    ErrorScanSensorErr,
    ErrorScanTopCoverOpenDuringCardSlotScanning,
    ErrorScanTopCoverOpenBeforeCardSlotScanning,
    ErrorScanCardInsertDuringADFScanning,
    ErrorScanNoCardInCardSlot,
    ErrorScanJamInCardSlot,
    ErrorScanInvalidAutoScanDuplexRequest,
    ErrorScanApplicationHostError,
    ErrorScanInvalidADFBusinessCardScanRequest,
    ErrorScanUnknown,
    InProcessing
}
